coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 5%
    patch:
      default:
        target: 80%
comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
# Updated Sun Nov  9 12:49:29 CET 2025
# Updated Sun Nov  9 12:52:36 CET 2025
