name: PowerShell Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  test:
    name: PowerShell Syntax Check
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install PowerShell
      run: |
        sudo apt-get update
        sudo apt-get install -y powershell

    - name: Test Script Syntax
      shell: pwsh
      run: |
        Write-Output "PowerShell version: $($PSVersionTable.PSVersion)"
        Write-Output "Testing script syntax..."
        $null = [System.Management.Automation.PSParser]::Tokenize((Get-Content ./vmware-vm-audit-dod-stig.ps1 -Raw), [ref]$null)
        Write-Output "✅ Script syntax is valid"

    - name: Test Examples Syntax
      shell: pwsh
      run: |
        Write-Output "Testing examples syntax..."
        Get-ChildItem examples/*.ps1 | ForEach-Object {
          Write-Output "Checking $($_.Name)..."
          $null = [System.Management.Automation.PSParser]::Tokenize((Get-Content $_.FullName -Raw), [ref]$null)
        }
        Write-Output "✅ All examples syntax valid"