name: PowerShell Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  checks: write

jobs:
  test:
    name: PowerShell Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install PowerShell
      run: |
        sudo apt-get update
        sudo apt-get install -y powershell

    - name: Install PowerCLI
      shell: pwsh
      run: |
        Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
        Install-Module -Name VMware.PowerCLI -Scope CurrentUser -Force -SkipPublisherCheck
        Install-Module -Name Pester -Scope CurrentUser -Force -MinimumVersion 5.0

    - name: Run Basic Tests
      shell: pwsh
      run: |
        Write-Host "PowerShell version: $($PSVersionTable.PSVersion)"
        Write-Host "Testing script syntax..."
        $null = [System.Management.Automation.PSParser]::Tokenize((Get-Content ./vmware-vm-audit-dod-stig.ps1 -Raw), [ref]$null)
        Write-Host "✅ Script syntax is valid"

    - name: Run PSScriptAnalyzer
      shell: pwsh
      continue-on-error: true
      run: |
        Install-Module -Name PSScriptAnalyzer -Force -Scope CurrentUser
        $results = Invoke-ScriptAnalyzer -Path ./vmware-vm-audit-dod-stig.ps1
        if ($results) {
          $results | Format-Table
          Write-Host "⚠️ PSScriptAnalyzer found issues (non-blocking)"
        } else {
          Write-Host "✅ No PSScriptAnalyzer issues found"
        }