name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup PowerShell
      uses: actions/setup-powershell@v1

    - name: Generate Changelog
      id: changelog
      run: |
        echo "## Changes" > CHANGELOG_TEMP.md
        git log --pretty=format:"- %s (%h)" $(git describe --tags --abbrev=0 HEAD^)..HEAD >> CHANGELOG_TEMP.md
        echo "changelog<<EOF" >> $GITHUB_OUTPUT
        cat CHANGELOG_TEMP.md >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Create Release Archive
      run: |
        mkdir -p release
        cp vmware-vm-audit-dod-stig.ps1 release/
        cp README.md release/
        cp LICENSE release/
        cp -r docs release/
        cp -r examples release/
        tar -czf vmware-vm-audit-dod-stig-${{ github.ref_name }}.tar.gz -C release .
        zip -r vmware-vm-audit-dod-stig-${{ github.ref_name }}.zip release/

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        body: ${{ steps.changelog.outputs.changelog }}
        files: |
          vmware-vm-audit-dod-stig-${{ github.ref_name }}.tar.gz
          vmware-vm-audit-dod-stig-${{ github.ref_name }}.zip
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}